# Generated by Django 5.2 on 2025-04-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('date', models.DateTimeField(help_text='Date and time when the event will occur')),
                ('location', models.CharField(help_text='Venue or location of the event', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional event poster or image', null=True, upload_to='events/images/')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the event', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the event was last updated')),
                ('organizer', models.ForeignKey(help_text='User who organizes the event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
    ]
